"""
Interactive setup wizard.

Single responsibility: guide the user through creating or updating a .env file.
"""

from __future__ import annotations

import getpass
from pathlib import Path

_ENV_FILE = Path(".env")

_SECRET_VARS = {"JIRA_TOKEN", "CONFLUENCE_TOKEN"}

_VARS: list[tuple[str, str, bool]] = [
    # (env var, description, required)
    ("JIRA_BASE_URL", "Jira base URL  e.g. https://your-org.atlassian.net", True),
    ("JIRA_TOKEN", "Jira personal access token", True),
    ("JIRA_PROJECT", "Jira project key to limit scope (strongly recommended)  e.g. MYPROJ", False),
    ("JIRA_FEATURE_TEAM", 'Feature team filter (optional)  e.g. "My Team"', False),
    ("CONFLUENCE_BASE_URL", "Confluence base URL  e.g. https://your-org.atlassian.net/wiki  (only needed for --publish)", False),
    ("CONFLUENCE_TOKEN", "Confluence personal access token  (only needed for --publish)", False),
    ("CONFLUENCE_PARENT_PAGE_ID", "Confluence parent page ID — numeric  (only needed for --publish)", False),
]


def _load_existing() -> dict[str, str]:
    """Read key=value pairs from .env if it exists."""
    values: dict[str, str] = {}
    if _ENV_FILE.exists():
        for line in _ENV_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, val = line.partition("=")
                values[key.strip()] = val.strip()
    return values


def _write_env(values: dict[str, str]) -> None:
    lines: list[str] = [
        "# Generated by story-points-analyzer setup",
        "",
        "# --- Always required ---",
    ]
    always = ["JIRA_BASE_URL", "JIRA_TOKEN"]
    optional_jira = ["JIRA_PROJECT", "JIRA_FEATURE_TEAM"]
    confluence = ["CONFLUENCE_BASE_URL", "CONFLUENCE_TOKEN", "CONFLUENCE_PARENT_PAGE_ID"]

    for key in always:
        val = values.get(key, "")
        lines.append(f"{key}={val}" if val else f"# {key}=")

    lines += ["", "# --- Optional: narrow the Jira query scope ---"]
    for key in optional_jira:
        val = values.get(key, "")
        lines.append(f"{key}={val}" if val else f"# {key}=")

    lines += ["", "# --- Required only when using --publish ---"]
    for key in confluence:
        val = values.get(key, "")
        lines.append(f"{key}={val}" if val else f"# {key}=")

    _ENV_FILE.write_text("\n".join(lines) + "\n")


def _mask(value: str) -> str:
    """Show only the last 4 characters of a secret."""
    if not value:
        return ""
    return "*" * max(0, len(value) - 4) + value[-4:]


def run_setup() -> None:
    """Interactive wizard to create or update .env."""
    existing = _load_existing()

    print()
    print("story-points-analyzer setup")
    print("=" * 40)
    if _ENV_FILE.exists():
        print(f"Updating existing {_ENV_FILE} — press Enter to keep the current value.\n")
    else:
        print(f"Creating {_ENV_FILE}\n")

    values: dict[str, str] = {}
    has_error = False

    for var, description, required in _VARS:
        current = existing.get(var, "")
        is_secret = var in _SECRET_VARS
        label = f"  {var}" + ("" if required else " (optional)")
        print(label)
        print(f"    {description}")

        if current:
            display = _mask(current) if is_secret else current
            print(f"    current: {display}")
            hint = "    (press Enter to keep): "
        else:
            hint = "    : "

        try:
            if is_secret:
                answer = getpass.getpass(hint).strip() or current
            else:
                answer = input(hint).strip() or current
        except (EOFError, KeyboardInterrupt):
            print("\nSetup cancelled.")
            return

        if required and not answer:
            print(f"    ✗ {var} is required.")
            has_error = True

        values[var] = answer
        print()

    if has_error:
        print("⚠  Some required values are missing. The .env file was not written.")
        print("   Re-run `story-points-analyzer setup` to try again.")
        return

    _write_env(values)
    print(f"✓ {_ENV_FILE} written.")
    print()
    print("Next steps:")
    print("  story-points-analyzer              # generate report.md locally")
    print("  story-points-analyzer --publish    # publish to Confluence")
